### ISSUE TITLE
defining the port is case sensitive

### ISSUE THREAD

**Issue by amccool** [richorama/OrleansDashboard#1]
<BootstrapProviders>
      <Provider Type="OrleansDashboard.Dashboard" Name="Dashboard" port="8088" />
    </BootstrapProviders>

port must be lowercase.   Perhaps just update the readme.md

**Comment by richorama** [comment]
It started off as `port`, and then I changed it to `Port` in this commit: 

https://github.com/richorama/OrleansDashboard/commit/6c09d9d63fd8c886c4cf51248a6d158192702512#diff-1695e6ec90ee151603a1e01d726cf858R54

It may be that you're looking at an older version of the code, and the readme is up-to-date?
